FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/packages

RUN pip install --no-cache-dir -U pip

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY packages packages
COPY apps/worker apps/worker

WORKDIR /app/apps/worker

CMD ["python", "-m", "worker.main"]

